import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/redux/Provider";
const inter = Inter({ subsets: ["latin"] });
import Headers from "@/components/header/Header";
export const metadata: Metadata = {
  title: "no-1 Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ReduxProvider>
          <Headers />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
